name: Laravel Test Before Merge

on:
  pull_request:
    branches:
      - main

jobs:
  laravel-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.1

      - name: Install Composer Dependencies
        run: composer install --no-progress --no-suggest

      - name: Copy .env
        run: cp .env.example .env

      - name: Generate App Key
        run: php artisan key:generate

      - name: Run Laravel Test
        run: php artisan test

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install HTMLHint & Stylelint
        run: |
          npm install -g htmlhint
          npm install -g stylelint stylelint-config-standard

      - name: Run HTML Lint
        run: htmlhint "resources/views/**/*.blade.php"

      - name: Run CSS Lint
        run: stylelint "resources/css/**/*.css"